### ISSUE TITLE
Set up autogitops deployment of loderunner-api/clientmode/ui to preprod

### ISSUE THREAD

**Issue by PurpleBriar** [retaildevcrews/ngsa-asb#102]
What:
Need to automate deployment of loderunner apps to preprod using autogitops

Why:
Demonstrate automated deployment of loderunner apps currently in dev clusters in preprod

When:

Where:
ngsa-asb-pre

## Tasks
- [x] Update autogitops to deploy loderunner apps to preprod
- [x] Create endpoints for deployed apps where needed (eg., loderunner-api)
- [x] Verify that resources are deployed correctly
- [x] Update documentation if necessary

## References:
- References retaildevcrews/wcnp/issues/958 (apps were initially deployed manually in preprod central, and need to be automated by setting up using autogitops and managing using flux)
